name: servicehisilicon

on:
  push:
    branches: [ sigc3 ]
  pull_request:
    branches: [ sigc3 ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: install prerequisites
      run: |
        sudo apt-get -q update
        sudo apt-get install automake
        sudo apt-get install git
        sudo apt-get install build-essential
        sudo apt-get install gettext
        sudo apt-get install python3-dev
        sudo apt-get install mm-common
    - name: build dependencies
      run: |
        echo installing libsigc++3
        pushd .
        cd /tmp
        git clone --depth 1 https://github.com/dbus-cxx/libsigc--3.0.git
        cd libsigc--3.0
        autoreconf -i
        ./configure
        make
        sudo make install
        popd      
    - name: compile python3
      run: |
        python3 -m compileall .
    - name: compile po files
      run: |
        find . -type f -name "*.po" -exec msgfmt {} -o {}.mo \;
        echo done!
